/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-119094-g3e32dc8b08-20250331"
#endif /* AVUTIL_FFVERSION_H */
